all : diskschedule resultCalculator

diskschedule : diskschedule.c
	gcc -o diskschedule diskschedule.c
resultCalculator : resultCalculator.c
	gcc -o resultCalculator resultCalculator.c -lm 
clean :
	rm diskschedule
	rm resultCalculator


